baseurl = "https://healthheroes.com/"
title = "HealthHeroes"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  titleCutting = false

  [[params.navlinks]]
  name = "about/"
  url = "about"

  [[params.navlinks]]
  name = "proposal/"
  url = "proposal"

  [[params.navlinks]]
  name = "poster/"
  url = "poster"
  
  [[params.navlinks]]
  name = "application/"
  url = "application"
  
  [[params.navlinks]]
  name = "research paper/"
  url = "research-paper"
